cloud:
  aws:
    credentials:
      access-key: AKIA3XPJ6NTMYOTL6QEL
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: festival-vin-bucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090